### ISSUE TITLE
Priority bug in PD-CLI?

### ISSUE THREAD

**Issue by xl483** [p4lang/p4factory#19]
I was trying to add a ternary match rule in PD-CLI , which requires a priority, and I worked out the syntax is `add_entry TABLE_NAME MATCH_FIELDS... ACTION_NAME ACTION_PARAMETERS... PRIORITY`. However actually trying to do this causes an unhandled exception in Python to be raised. Some digging reveals that `add_entry` in `pd_thrift_client.py` puts the action specification before the priority:

```python
if action_spec_tuple != ():
    add_entry_parameters.append(self.get_action_spec(action_name, action_spec_tuple))

if priority != None:
    add_entry_parameters.append(priority)
```

whereas the function at the other end of the RPC is expecting the action specification *after* the priority. Swapping the order of the above two blocks seems to fix the problem.

**Comment by antoninbas** [comment]
Could you submit a PD-CLI patch for this (as a pull request) ? It seems that you have the code already. Thanks.

**Comment by xl483** [comment]
Done!

**Comment by antoninbas** [comment]
Thanks. Before I can merge your contribution, I need to get a signed Apache CLA from you. We are working on a better system to accept signed CLAs, but for now, could you send me an email at antonin@barefootnetworks.com, so that I can put you in touch with the p4.org representative in charge of this? I could not find your email address.
