### ISSUE TITLE
run simple_router target error :No handlers could be found for logger "thrift.transport.TSocket"

### ISSUE THREAD

**Issue by cool-leng** [p4lang/p4factory#196]
I get the following error when I run p4factory/targets/simple_router/ as README:
run these cli
 ./install_deps.sh

sudo p4factory/tools/veth_setup.sh

cd p4factory
./autogen.sh
./configure

cd p4factory/targets/simple_router/
make bm
./run_demo.bash

./run_add_demo_entries.bash

these are part of records
 root@ccf:~/p4/p4factory/targets/simple_router# make bm
    Compiling : bm::pd_rpc_server.cpp
    Compiling : bm::p4_pd_rpc_constants.cpp
    Compiling : bm::conn_mgr_pd_rpc_constants.cpp
    Compiling : bm::mc_pd_rpc_constants.cpp
    Compiling : bm::devport_mgr_pd_rpc_constants.cpp
    Compiling : bm::res_constants.cpp
    Compiling : bm::p4_pd_rpc_types.cpp
    Compiling : bm::conn_mgr_pd_rpc_types.cpp
    Compiling : bm::mc_pd_rpc_types.cpp
    Compiling : bm::devport_mgr_pd_rpc_types.cpp
    Compiling : bm::res_types.cpp
    Compiling : bm::simple_router.cpp
    Compiling : bm::conn_mgr.cpp
    Compiling : bm::mc.cpp
    Compiling : bm::devport_mgr.cpp
    Creating : bm.a
    Linking: bm
cp /root/p4/p4factory/targets/simple_router/build//bin/bm behavioral-model
cp -r /root/p4/p4factory/targets/simple_router/build//thrift/* /root/p4/p4factory/targets/simple_router/tests/pd_thrift/

root@ccf:~/p4/p4factory/targets/simple_router# ./run_demo.bash 
*** Creating network
*** Adding hosts:
h1 h2 
*** Adding switches:
s1 
*** Adding links:
(h1, s1) (h2, s1) 
*** Configuring hosts
h1 h2 
*** Starting controller
*** Starting 1 switches
s1 Starting P4 switch s1
/root/p4/p4factory/targets/simple_router/behavioral-model --name s1 --dpid 0000000000000001 -i s1-eth1 -i s1-eth2 --listener 127.0.0.1:11111 --pd-server 127.0.0.1:22222 
switch has been started

**********
h1
default interface: eth0	10.0.0.10	00:04:00:00:00:00
**********
**********
h2
default interface: eth0	10.0.1.10	00:04:00:00:00:01
**********
Ready !
*** Starting CLI:
mininet> 
mininet> 

root@ccf:~/p4/p4factory/targets/simple_router# ./run_add_demo_entries.bash 
No handlers could be found for logger "thrift.transport.TSocket"
Traceback (most recent call last):
  File "../../cli/pd_cli.py", line 677, in <module>
    main(sys.argv[1:])
  File "../../cli/pd_cli.py", line 665, in main
    pd_cli = PdCli(p4_name, thrift_client_module, thrift_server, port)
  File "../../cli/pd_cli.py", line 35, in __init__
    self._thrift_client = pd_thrift_client.ThriftClient(self._module, thrift_server, port, self._p4_name)
  File "/root/p4/p4factory/cli/pd_thrift_client.py", line 55, in __init__
    self.setup(hostname, port)
  File "/root/p4/p4factory/cli/pd_thrift_client.py", line 77, in setup
    self._transport.open()
  File "/usr/local/lib/python2.7/dist-packages/thrift/transport/TTransport.py", line 152, in open
    return self.__trans.open()
  File "/usr/local/lib/python2.7/dist-packages/thrift/transport/TSocket.py", line 113, in open

**Comment by antoninbas** [comment]
Before looking any further, could you try running the following and see if it fixes your issue:
```
sudo mn -c 
sudo killall behavioral-model 
redis-cli FLUSHALL
```

The `No handlers could be found for logger` message can be safely ignored.
Looks like the behavioral-model executable is not starting properly. The most likely explanation is that the redis-server is not running. You may want to try running `redis-cli ping` in a terminal. If you get an error, you will need to figure out how to start the redis-server. If the command returns successfully (i.e. if you get a `PONG`), then try running `sudo /home/antonin/Documents/p4lang/p4factory/targets/simple_router/behavioral-model --name s1 --dpid 0000000000000001 --listener 127.0.0.1:11111 --pd-server 127.0.0.1:22222` and look at the output to check for an error.

Note that the software you are trying to use is deprecated and we are hardly maintaining it anymore. We now use the second version of the behavioral-model, aka bmv2, instead of the initial version, which you are trying to use now. We also no longer use p4factory as a place to develop new P4 programs. See this p4-dev thread: http://lists.p4.org/pipermail/p4-dev_lists.p4.org/2017-March/000794.html

**Comment by cool-leng** [comment]
Hi,antoninbas

Thank you very much for your method,I tried the cli
 sudo mn -c 
sudo killall behavioral-model 
redis-cli FLUSHALL

It's does work well,thank you,again!
